//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskPriority
    {
        public TaskPriority()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public long TaskPriorityID { get; set; }
        public string PriorityText { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CustomCSS { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
