//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskComments = new HashSet<TaskComment>();
        }
    
        public long TaskID { get; set; }
        public string Text { get; set; }
        public long TaskStatusID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public Nullable<System.DateTime> DeadLineDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> AssingedToID { get; set; }
        public Nullable<System.DateTime> AssingedDate { get; set; }
        public Nullable<long> TaskPriorityID { get; set; }
    
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual TeamMember TeamMember { get; set; }
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        public virtual TaskPriority TaskPriority { get; set; }
    }
}
