//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public long TaskID { get; set; }
        public Nullable<long> ParentTaskID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long TaskStatusID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public long TaskTypeID { get; set; }
    
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual TaskType TaskType { get; set; }
    }
}
