//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatus
    {
        public TaskStatus()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public long TaskStatusID { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
